language: node_js

node_js:
    - "5"
    - "4"
    #- iojs   No longer maintained
    #- "0.12" Maintenance ending 2017-04-01
    #- "0.10" Maintenance ending 2016-10-01
    #- "0.8"  Not supported by mocha
    #- "0.6"  Script works, tests don't

after_success:
    - npm install istanbul codecov
    - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec
    - cat ./coverage/coverage.json | ./node_modules/.bin/codecov
